name: Android CI

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew assembleRelease lintVitalRelease

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-output
        path: app/build/outputs/apk/
        retention-days: 7
